

spring:
  application:
    name: authentication-aouth2
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost/users_ap
    username: chiheb  
    password: 1234
    driverClassName: org.postgresql.Driver
 
google:
  id: 660220038969-1gl4foc68ueti12oheh6tpcfshpgb70p.apps.googleusercontent.com
mySecret:
  password: 1234
server:
  port: 8081
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
